package com.samwoo.slot.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.samwoo.slot.database.Rank;

import com.samwoo.slot.greendao.RankDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig rankDaoConfig;

    private final RankDao rankDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        rankDaoConfig = daoConfigMap.get(RankDao.class).clone();
        rankDaoConfig.initIdentityScope(type);

        rankDao = new RankDao(rankDaoConfig, this);

        registerDao(Rank.class, rankDao);
    }
    
    public void clear() {
        rankDaoConfig.clearIdentityScope();
    }

    public RankDao getRankDao() {
        return rankDao;
    }

}
